### ISSUE TITLE
Interface GSM Module with BB-WI

### ISSUE THREAD

**Issue by zrajani** [zrajani/iLETTERBOX_CAPSTONE_PROJECT_EMBT_F2020#19]
Using part one of interfacing completed without any flaws. Now we shall complete phase two of the interfacing i.e. once the letter is detected by the IR sensor the LED goes high now along with the LED going high one should also send an SMS to the user intimating that a letter was deposited in the letter box. 

All issues pertaining to this interfacing shall be posted in this. Please only submit the changes when issue #12 is closed

**Comment by zrajani** [comment]
As mentioned in the proposal we are supposed to code in the C/C++ language but the problem occurs that we have no libraries readily available thus we are facing an issue to find one else as mentioned in the proposal we might have to deviate to python or find a more efficient solution.

**Comment by zrajani** [comment]
Referring to Issue #1 and  new forum link [Glitter](https://gitter.im/mirkix/BBBMINI?utm_source=ios&utm_medium=link&utm_campaign=ios-share-link) we posted requesting some help to get the GSM coded completely in C thus we see it was a previously opened question and the following information was collected:

1.  - [ ]  One can completely write a new library function like as in a complete header file which can support the GSM Module 
2.  - [x]  Take the help of another programming language which supports the GSM Module like bonescript or Python
3.  - [ ]  Connect a master slave connection like a Beaglebone (master device) and slave device like Arduino Uno/Rasp. Pi/ Arduino Nano etc. 

We choose the second option the reason for it being due the option 1 is good enough to learn and train yourself to code but since the task needs to be completed in a simulated time and writing a complete new header file will be time consuming as to we need to get to depth of may studying the module or even the layers of how the C language is written and use them to integrate the GSM module in code. Thus we can try it once we have got the project working and we have then sufficient time to code or may be leave it for the future scope and work upon it after the project for self-learning/ development and contribute back so others may use it for their work in the future. 

### _*To make a point since we use Arduino Cape SIM900 thus it shows that we can write a library but since the codes for the Arduino are written in C/C++ but with different root  structuring and provides most of the functions from the Wiring project thus one needs to make a complete detailed study on this aspects before making a library thus at this moment it looks difficult but an attempt shall be made if time permits or in the future definitely._   

Option 2 looks feasible at this stage as because in the proposal submitted we see that we had mentioned that we may require to take help of some other programming language like python iffy C/C++ library is not found. Thus this complies with the proposal as well thus we wont have to change or wait for any approval. Lastly, option 3 could also be done as since the module is compatible and is meant for the Arduino thus we can easily integrate it with Arduino but the only problem being need to wait for an approval and also changes in the block and increase in the hardware as well. Also since python is fast in execution thus, will make the system fast.

**Comment by zrajani** [comment]
> As mentioned in the proposal we are supposed to code in the C/C++ language but the problem occurs that we have no libraries readily available thus we are facing an issue to find one else as mentioned in the proposal we might have to deviate to python or find a more efficient solution.

Referring to Issue #1 and new forum link Glitter we posted requesting some help to get the GSM coded completely in C thus we see it was a previously opened question and the following information was collected:

 One can completely write a new library function like as in a complete header file which can support the GSM Module
 Take the help of another programming language which supports the GSM Module like bonescript or Python
 Connect a master slave connection like a Beaglebone (master device) and slave device like Arduino Uno/Rasp. Pi/ Arduino Nano etc.
We choose the second option the reason for it being due the option 1 is good enough to learn and train yourself to code but since the task needs to be completed in a simulated time and writing a complete new header file will be time consuming as to we need to get to depth of may studying the module or even the layers of how the C language is written and use them to integrate the GSM module in code. Thus we can try it once we have got the project working and we have then sufficient time to code or may be leave it for the future scope and work upon it after the project for self-learning/ development and contribute back so others may use it for their work in the future.

*To make a point since we use Arduino Cape SIM900 thus it shows that we can write a library but since the codes for the Arduino are written in C/C++ but with different root structuring and provides most of the functions from the Wiring project thus one needs to make a complete detailed study on this aspects before making a library thus at this moment it looks difficult but an attempt shall be made if time permits or in the future definitely.
Option 2 looks feasible at this stage as because in the proposal submitted we see that we had mentioned that we may require to take help of some other programming language like python iffy C/C++ library is not found. Thus this complies with the proposal as well thus we wont have to change or wait for any approval. Lastly, option 3 could also be done as since the module is compatible and is meant for the Arduino thus we can easily integrate it with Arduino but the only problem being need to wait for an approval and also changes in the block and increase in the hardware as well. Also since python is fast in execution thus, will make the system fast.

**Comment by zrajani** [comment]
> As mentioned in the proposal we are supposed to code in the C/C++ language but the problem occurs that we have no libraries readily available thus we are facing an issue to find one else as mentioned in the proposal we might have to deviate to python or find a more efficient solution.

Referring to Issue #1 and new forum link Glitter we posted requesting some help to get the GSM coded completely in C thus we see it was a previously opened question and the following information was collected:

 One can completely write a new library function like as in a complete header file which can support the GSM Module
 Take the help of another programming language which supports the GSM Module like bonescript or Python
 Connect a master slave connection like a Beaglebone (master device) and slave device like Arduino Uno/Rasp. Pi/ Arduino Nano etc.
We choose the second option the reason for it being due the option 1 is good enough to learn and train yourself to code but since the task needs to be completed in a simulated time and writing a complete new header file will be time consuming as to we need to get to depth of may studying the module or even the layers of how the C language is written and use them to integrate the GSM module in code. Thus we can try it once we have got the project working and we have then sufficient time to code or may be leave it for the future scope and work upon it after the project for self-learning/ development and contribute back so others may use it for their work in the future.

### _*To make a point since we use Arduino Cape SIM900 thus it shows that we can write a library but since the codes for the Arduino are written in C/C++ but with different root structuring and provides most of the functions from the Wiring project thus one needs to make a complete detailed study on this aspects before making a library thus at this moment it looks difficult but an attempt shall be made if time permits or in the future._

Option 2 looks feasible at this stage as because in the proposal submitted we see that we had mentioned that we may require to take help of some other programming language like python iffy C/C++ library is not found. Thus this complies with the proposal as well thus we wont have to change or wait for any approval. Lastly, option 3 could also be done as since the module is compatible and is meant for the Arduino thus we can easily integrate it with Arduino but the only problem being need to wait for an approval and also changes in the block and increase in the hardware as well. Also since python is fast in execution thus, will make the system fast.

**Comment by zrajani** [comment]
> As mentioned in the proposal we are supposed to code in the C/C++ language but the problem occurs that we have no libraries readily available thus we are facing an issue to find one else as mentioned in the proposal we might have to deviate to python or find a more efficient solution.

Referring to Issue #1 and new forum link [Gitter*](https://gitter.im/mirkix/BBBMINI?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) we posted requesting some help to get the GSM coded completely in C thus we see it was a previously opened question and the following information was collected:

**_*Gitter is not official forum for discussion it was created for a project BeagleBone ArduPilot DIY Cape but people do discuss many issues related to protocols being used as this cape has used mostly variety of protocols ranging from I2C, UART, SPI and CAN. The Creator of the forum is [Mirko Denecke](https://github.com/mirkix/BBBMINI)_**

 One can completely write a new library function like as in a complete header file which can support the GSM Module
 Take the help of another programming language which supports the GSM Module like bonescript or Python
 Connect a master slave connection like a Beaglebone (master device) and slave device like Arduino Uno/Rasp. Pi/ Arduino Nano etc.
We choose the second option the reason for it being due the option 1** is good enough to learn and train yourself to code but since the task needs to be completed in a simulated time and writing a complete new header file will be time consuming as to we need to get to depth of may studying the module or even the layers of how the C language is written and use them to integrate the GSM module in code. Thus we can try it once we have got the project working and we have then sufficient time to code or may be leave it for the future scope and work upon it after the project for self-learning/ development and contribute back so others may use it for their work in the future.

### _**To make a point since we use Arduino Cape SIM900 thus it shows that we can write a library but since the codes for the Arduino are written in C/C++ but with different root structuring and provides most of the functions from the Wiring project thus one needs to make a complete detailed study on this aspects before making a library thus at this moment it looks difficult but an attempt shall be made if time permits or in the future._

Option 2 looks feasible at this stage as because in the proposal submitted we see that we had mentioned that we may require to take help of some other programming language like python iffy C/C++ library is not found. Thus this complies with the proposal as well thus we wont have to change or wait for any approval. Lastly, option 3 could also be done as since the module is compatible and is meant for the Arduino thus we can easily integrate it with Arduino but the only problem being need to wait for an approval and also changes in the block and increase in the hardware as well. Also since python is fast in execution thus, will make the system fast.

**Comment by zrajani** [comment]
> As mentioned in the proposal we are supposed to code in the C/C++ language but the problem occurs that we have no libraries readily available thus we are facing an issue to find one else as mentioned in the proposal we might have to deviate to python or find a more efficient solution.

Referring to Issue #1 and new forum link [Gitter*](https://gitter.im/mirkix/BBBMINI?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) we found. We posted requesting some help to get the GSM coded completely in C thus we saw that there were previously opened question and the following information was collected from the forums:

**_*Gitter is not official forum for discussion it was created for a project BeagleBone ArduPilot DIY Cape but people do discuss many issues related to protocols being used as this cape has used mostly variety of protocols ranging from I2C, UART, SPI and CAN. The Creator of the forum is [Mirko Denecke](https://github.com/mirkix/BBBMINI)_**

- [ ] 1. One can completely write a new library function like as in a complete header file which can support the GSM Module
- [x] 2. Take the help of another programming language which supports the GSM Module like bonescript or Python
- [ ] 3. Connect a master slave connection like a Beaglebone (master device) and slave device like Arduino Uno/Rasp. Pi/ Arduino Nano etc.

We choose the second option the reason for it being due the option 1** is good enough to learn and train yourself to code but since the task needs to be completed in a simulated time and writing a complete new header file will be time consuming as to we need to get to depth of may studying the module or even the layers of how the C language is written and use them to integrate the GSM module in code. Thus we can try it once we have got the project working and we have then sufficient time to code or may be leave it for the future scope and work upon it after the project for self-learning/ development and contribute back so others may use it for their work in the future.

### _**To make a point since we use Arduino Cape SIM900 thus it shows that we can write a library but since the codes for the Arduino are written in C/C++ but with different root structuring and provides most of the functions from the Wiring project thus one needs to make a complete detailed study on this aspects before making a library thus at this moment it looks difficult but an attempt shall be made if time permits or in the future._

Option 2 looks feasible at this stage as because in the proposal submitted we see that we had mentioned that we may require to take help of some other programming language like python iffy C/C++ library is not found. Thus this complies with the proposal as well thus we wont have to change or wait for any approval. Lastly, option 3 could also be done as since the module is compatible and is meant for the Arduino thus we can easily integrate it with Arduino but the only problem being need to wait for an approval and also changes in the block and increase in the hardware as well. Also since python is fast in execution thus, will make the system fast.

**Comment by zrajani** [comment]
The python code written for the GSM. But we are facing the following issues now:
1. Finding a way to integrate it with the C codes
2. Python code is throwing errors for "pyserial" package

**Comment by zrajani** [comment]
> The python code is written for the GSM. But we are facing the following issues now:
> 
> 1. Finding a way to integrate it with the C codes
> 2. Python code is throwing errors for the "pyserial" package

The first issue was resolved using the command `system('command_name')` which is available in the stdlib.h header file with this command we were able to run the scripts written in python from the C code that we had previous written while dealing with Issue #12 

The second issue was due to the absence of the pyserial package module on the BB-WI thus to resolve this issue we had to install the module which could be done using the `pip` command. pip is a python interface package manager which helps us in getting all the required modules downloaded to the machine. But in order to use this `pip` command, one needs to install it on the machine using the command `sudo apt install pip` and then download the required packages/modules using `pip install pyserial` in place of pyserial one can mention the package that one wishes to install. If one wishes to uninstall any package then he/she may use the command `pip uninstall package_name`

**Comment by zrajani** [comment]
While working to interface the GSM with BB-WI we had some issues that we faced in the testing hardware mentioned at #6 of this project. That is when the shield was given the power we were required to press the power key in order to get the module connected to the network. The press has to be for a minimum of 2 seconds. In this way, we verified that GSM was connected to the network by looking at the network LED on the module.

Secondly, we saw that when the program was compiled which was success and as mentioned that if the GSM was able to send messages then a message should be displayed on the screen as "Message Sent" and this was also displayed on the screen. but the issue was that we never received an SMS on the desired cell phone. Which was strange to us.

**Comment by zrajani** [comment]
> While working to interface the GSM with BB-WI we had some issues that we faced in the testing hardware mentioned at #6 of this project. That is when the shield was given the power we were required to press the power key in order to get the module connected to the network. The press has to be for a minimum of 2 seconds. In this way, we verified that GSM was connected to the network by looking at the network LED on the module.
> 
> Secondly, we saw that when the program was compiled which was a success and as mentioned that if the GSM was able to send messages then a message should be displayed on the screen as "Message Sent" and this was also displayed on the screen. but the issue was that we never received an SMS on the desired cell phone. Which was strange to us.

To get the issue mentioned resolved we tried the following methods: 

1. The first step was to check the physical connection with the GSM Module and we found that we connected transmitter to transmitter and receiver to the receiver which was a silly mistake and thus this was corrected immediately 
2. We tried to check for the baud rates of the GSM module and the cell phone and we could see that the maximum rate for serial communication is around 115200 baud rate with 8N1 coding thus we set the baud rate of 115200 as we required higher speed with 4G phones. 
3. Lastly we check if we have configured the pins as UART pins which weren't done thus we used the command `config-pin Px.** mode` where x stands for expansion header and ** stands for the pin number.

**Comment by mikeshams** [comment]
"....We tried to check for the baud rates of the GSM module and the cell phone ...."
The thing that we discussed in class
